import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='w-full h-screen bg-stone-900'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-full flex flex-col justify-center items-center'>
        <h1 className='text-xl'>DJ Meyers</h1>
        <p>Placeholder</p>
      </main>
    </div>
  )
}
